FROM python:3.12-slim

WORKDIR /app

# Сначала копируем только манифесты зависимостей
COPY backend/pyproject.toml backend/poetry.lock ./

RUN pip install --upgrade pip \
 && pip install poetry \
 && poetry config virtualenvs.create false \
 && poetry install --without dev --no-root

# Потом уже копируем весь код
COPY backend/ ./

ENV PORT=8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]