# Dockerfile-backend

FROM python:3.12-slim

WORKDIR /app/backend

COPY backend/pyproject.toml backend/poetry.lock ./
RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --without dev --no-root

COPY backend/ ./backend

ENV PORT=8080

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080"]