[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["xml-aztec <asankozhoevn@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["all"], version = "^0.115.12"}
sqlalchemy = "^2.0.41"
aiosqlite = "^0.21.0"
asyncpg = "^0.30.0"
greenlet = "^3.2.2"
pydantic = "^2.11.5"
pydantic-settings = "^2.9.1"
alembic = "^1.16.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
bcrypt = "^3.2.0"
python-jose = {extras = ["cryptography"], version = "^3.5.0"}
qrcode = "^8.2"
pillow = "^11.3.0"


[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"
mypy = "^1.15.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
