"""add search vector columns and gin indexes

Revision ID: 1bb23a364f65
Revises: 4b27405321b7
Create Date: 2026-08-31 13:05:00.846265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1bb23a364f65'
down_revision: Union[str, None] = '4b27405321b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(name,'') || ' ' || coalesce(phone,'') || ' ' || coalesce(email,''))", persisted=True), nullable=True))
    op.create_index('ix_customers_search_vector', 'customers', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('orders', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(id::text,'') || ' ' || coalesce(note,'') || ' ' || coalesce(delivery_address,''))", persisted=True), nullable=True))
    op.create_index('ix_orders_search_vector', 'orders', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('products', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(name,'') || ' ' || coalesce(sku,'') || ' ' || coalesce(barcode,''))", persisted=True), nullable=True))
    op.create_index('ix_products_search_vector', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('suppliers', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(name,'') || ' ' || coalesce(contact_person,''))", persisted=True), nullable=True))
    op.create_index('ix_suppliers_search_vector', 'suppliers', ['search_vector'], unique=False, postgresql_using='gin')
    op.add_column('users', sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('russian', coalesce(full_name,'') || ' ' || coalesce(email,''))", persisted=True), nullable=True))
    op.create_index('ix_users_search_vector', 'users', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_search_vector', table_name='users', postgresql_using='gin')
    op.drop_column('users', 'search_vector')
    op.drop_index('ix_suppliers_search_vector', table_name='suppliers', postgresql_using='gin')
    op.drop_column('suppliers', 'search_vector')
    op.drop_index('ix_products_search_vector', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'search_vector')
    op.drop_index('ix_orders_search_vector', table_name='orders', postgresql_using='gin')
    op.drop_column('orders', 'search_vector')
    op.drop_index('ix_customers_search_vector', table_name='customers', postgresql_using='gin')
    op.drop_column('customers', 'search_vector')
    # ### end Alembic commands ###
