"""money columns to numeric 12 2

Переводит все денежные колонки на NUMERIC(12,2) (аудит M1) и kpi_percent —
на NUMERIC(6,2) (M2).

Зачем: часть колонок хранилась в double precision (products.price,
products.cost_price, supply_items.*, monthly_targets.target_amount), а часть —
в NUMERIC, и они смешивались в одном потоке вычислений: цена товара из float
попадала в NUMERIC-позицию заказа, а расчёт прибыли вычитал float-себестоимость
из NUMERIC-выручки, накапливая ошибку округления в отчёте о прибылях.

Прежний NUMERIC(10,2) вдобавок ограничивал сумму значением 99 999 999,99, что
для оптовой сделки в сомах — недостаточный запас.

Конверсия из double precision идёт через явный ROUND(col::numeric, 2): без
USING результат зависел бы от неявного приведения, а так поведение задано
прямо и одинаково для всех таких колонок.

kpi_percent был INTEGER, хотя в него пишется значение вида 87.35 — база
молча округляла его до 87. Существующие целые значения при расширении типа
сохраняются как есть.

Revision ID: 3d3b59ea8e63
Revises: f8420f4bbfd1
Create Date: 2026-09-04 10:51:19.790152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d3b59ea8e63'
down_revision: Union[str, None] = 'f8420f4bbfd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('monthly_targets', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='ROUND(target_amount::numeric, 2)',
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'final_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('orders', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'finalized_total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('payment_methods', 'surcharge_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('payrolls', 'kpi_percent',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('products', 'cost_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='ROUND(cost_price::numeric, 2)',
               existing_nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='ROUND(price::numeric, 2)',
               existing_nullable=False)
    op.alter_column('supply_items', 'cost_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='ROUND(cost_price::numeric, 2)',
               existing_nullable=True)
    op.alter_column('supply_items', 'unit_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               postgresql_using='ROUND(unit_price::numeric, 2)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('supply_items', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('supply_items', 'cost_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('products', 'cost_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.alter_column('payrolls', 'kpi_percent',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('payment_methods', 'surcharge_percent',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'finalized_total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('orders', 'total_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('order_items', 'final_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('order_items', 'unit_price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('monthly_targets', 'target_amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
