"""add order returns and defective stock

Revision ID: 9070ef4d4947
Revises: 1bb23a364f65
Create Date: 2026-08-31 14:16:48.991068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9070ef4d4947'
down_revision: Union[str, None] = '1bb23a364f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'approved', 'rejected', 'completed', name='returnstatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_returns_id'), 'order_returns', ['id'], unique=False)
    op.create_index('ix_order_returns_order_id', 'order_returns', ['order_id'], unique=False)
    op.create_index('ix_order_returns_status', 'order_returns', ['status'], unique=False)
    op.create_table('order_return_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_return_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition', sa.Enum('resalable', 'defective', name='returnitemcondition'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_return_id'], ['order_returns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_return_items_id'), 'order_return_items', ['id'], unique=False)
    op.add_column('product_stock', sa.Column('defective_quantity', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_stock', 'defective_quantity')
    op.drop_index(op.f('ix_order_return_items_id'), table_name='order_return_items')
    op.drop_table('order_return_items')
    op.drop_index('ix_order_returns_status', table_name='order_returns')
    op.drop_index('ix_order_returns_order_id', table_name='order_returns')
    op.drop_index(op.f('ix_order_returns_id'), table_name='order_returns')
    op.drop_table('order_returns')
    # ### end Alembic commands ###
