"""add fk indexes and non-negative stock constraints

Revision ID: b457c436b04d
Revises: aa3d7bc4d8fd
Create Date: 2026-09-03 22:40:00.803912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b457c436b04d'
down_revision: Union[str, None] = 'aa3d7bc4d8fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_product_id'), 'order_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_orders_branch_id'), 'orders', ['branch_id'], unique=False)
    op.create_index(op.f('ix_orders_confirmed'), 'orders', ['confirmed'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_index(op.f('ix_orders_status_id'), 'orders', ['status_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_user_id_created_at', 'orders', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_orders_warehouse_id'), 'orders', ['warehouse_id'], unique=False)
    op.create_index(op.f('ix_product_stock_warehouse_id'), 'product_stock', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###

    # CHECK-ограничения alembic автогенерацией не сравнивает — добавлены вручную.
    #
    # Сначала подчищаем данные: до появления блокировок в app/utils/stock.py
    # конкурентное подтверждение двух заказов на один товар могло увести
    # остаток в минус, и такие строки в существующей базе уже могут быть.
    # Без этого CREATE CONSTRAINT просто упал бы при накатке.
    op.execute(
        """
        UPDATE product_stock
        SET quantity = GREATEST(quantity, 0),
            reserved = GREATEST(reserved, 0),
            defective_quantity = GREATEST(defective_quantity, 0)
        WHERE quantity < 0 OR reserved < 0 OR defective_quantity < 0
        """
    )

    op.create_check_constraint(
        "ck_product_stock_quantity_non_negative", "product_stock", "quantity >= 0"
    )
    op.create_check_constraint(
        "ck_product_stock_reserved_non_negative", "product_stock", "reserved >= 0"
    )
    op.create_check_constraint(
        "ck_product_stock_defective_non_negative",
        "product_stock",
        "defective_quantity >= 0",
    )


def downgrade() -> None:
    op.drop_constraint(
        "ck_product_stock_defective_non_negative", "product_stock", type_="check"
    )
    op.drop_constraint(
        "ck_product_stock_reserved_non_negative", "product_stock", type_="check"
    )
    op.drop_constraint(
        "ck_product_stock_quantity_non_negative", "product_stock", type_="check"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_stock_warehouse_id'), table_name='product_stock')
    op.drop_index(op.f('ix_orders_warehouse_id'), table_name='orders')
    op.drop_index('ix_orders_user_id_created_at', table_name='orders')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_confirmed'), table_name='orders')
    op.drop_index(op.f('ix_orders_branch_id'), table_name='orders')
    op.drop_index(op.f('ix_order_items_product_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    # ### end Alembic commands ###
